### ISSUE TITLE
cannot get init_mapblock() to work

### ISSUE THREAD

**Issue by ghost** [LeMagnesium/python-minetest#7]
here is my rewrite of the map preloading script which:
1. uses your new libminetest rewrite
2. includes landcover
3. tries to process the source images in 16x16 footprints and splits the resulting elevation values into 16 m sections so that setting nodes can be done by block

in particular I am stumped on the loading of a recently initialized map block. could map.MapInterface.init_mapblock() return the blockID or the MapBlock itself? instead I am trying to load the block immediately after init_mapblock with the same blockpos, please see line 115:

https://gist.github.com/bobombolo/1e430eff993b7029b1030582d725f164#file-preload-py

<pre>
2016-04-05 11:14:58,453 map:__init__                 :35   DEBUG    MapBlock obj
ect initiated at (176, 0, 0)
2016-04-05 11:14:58,453 map:load                     :480  DEBUG    Mapblock 176
 not found
Traceback (most recent call last):
  File "preload.py", line 120, in <module>
    map_block.set_node(node["pos"], cover[node["lclu"]])
AttributeError: 'NoneType' object has no attribute 'set_node'
</pre>

anyway this script is close to working...

now that the script handles the nodes block by block, do you see any way to speed things up? maybe by calling implode() directly or somehow avoiding repeated calls to methods that convert positions and/or test to see if we are in the right mapblock (since we are for sure)?

**Comment by bobombolo** [comment]
I have commented out these offending lines about loading blocks and am trying to use the mapInterface set node directly but am getting an issue with a locked database error. If I comment out line 45 where I empty_map() I don't get this error... here is the traceback:

<pre>
2016-04-05 11:40:51,468 map:init_mapblock            :622  DEBUG    Init mapbloc
k at 176
2016-04-05 11:40:51,468 map:__init__                 :35   DEBUG    MapBlock obj
ect initiated at (176, 0, 0)
2016-04-05 11:40:51,484 map:load_mapblock            :591  DEBUG    Loaded mapbl
ock at 45056
Traceback (most recent call last):
  File "C:\Python34\lib\libminetest\map.py", line 468, in read
    self.cur.execute("SELECT * from blocks where pos = {0}".format(blockID))
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "preload.py", line 122, in <module>
    map_interface.set_node(pos, cover[node["lclu"]])
  File "C:\Python34\lib\libminetest\map.py", line 646, in set_node
    if not self.check_for_pos(mapblockpos):
  File "C:\Python34\lib\libminetest\map.py", line 631, in check_for_pos
    return self.load_mapblock(mapblockpos)
  File "C:\Python34\lib\libminetest\map.py", line 592, in load_mapblock
    data = self.container.load(blockID)
  File "C:\Python34\lib\libminetest\map.py", line 478, in load
    data = self.read(blockID)
  File "C:\Python34\lib\libminetest\map.py", line 470, in read
    raise MapError(err)
libminetest.errors.MapError: database is locked
</pre>

**Comment by bobombolo** [comment]
I'm also having issues with line 121 : map_interface.set_node(node["pos"], cover[node["lclu"]])

no variation of the position argument as a Pos, a string, or the {"x": x, "y":y,"z":z} format is working. always an error is thrown such as:

<pre>
Traceback (most recent call last):
  File "preload.py", line 122, in <module>
    map_interface.set_node(node["pos"], cover[node["lclu"]])
  File "C:\Python34\lib\libminetest\map.py", line 644, in set_node
    mapblock = determineMapBlock(pos)
  File "C:\Python34\lib\libminetest\utils.py", line 37, in determineMapBlock
    posx = floor(pos.x / 16)
AttributeError: 'dict' object has no attribute 'x'
</pre>

**Comment by Lymkwi** [comment]
> libminetest.errors.MapError: database is locked

This just means another program is working on your database.

> I have some confusion regarding map vessels vs map interfaces, different ways of writing a position (Pos class, {x,y,z}, int, blockID, internal nodeID from 0-4096, etc) 

Yes I have been confused as well for a while. Poses work a different way now, and I'll write documentation to detail the needed types for parameters. Basically, a position is relative to your container. The same Pos object can refer to two nodes depending on the container you'll use that function with. A Pos object (from libminetest.utils), which is now initialized like that :

``` python
pos = libminetest.utils.Pos(x, y, z)
```

That pos object is just a tuple of those 3 values, with some useful functions, like a convertion function to a unique integer in a container. To make this convertion, the functions needs a parameter which is called `max_val` and represents the maximum (unreachable) coordinate value.

> AttributeError: 'dict' object has no attribute 'x'

That function needed a Pos object, so if you give it a dict, it won't find the appropriate fields.

> AttributeError: 'NoneType' object has no attribute 'set_node'

I like that one; it means you tried to use a none object's set_node field, which doesn't exist : MapVessel.load gave you a None object because it didn't find your mapblock.

**Comment by bobombolo** [comment]
>locked database
yes but this "other program" is just the same script. it seems like the mapVessel and mapInterface are competing with eachother and possibly that the empty_map() routine is not unlocking or not finishing in time for the other class to start modifying the db in the same script: https://gist.github.com/bobombolo/1e430eff993b7029b1030582d725f164#file-preload-py-L42-L45
I am not sure of the relationship between vessel and interface, I need one to set the cache size, but the other to do actual manipulations, but they don't seem to relate to eachother. anyway, I think the problem is with empty_map, because if I comment that out, there is no lock issue

>AttributeError: 'NoneType' object has no attribute 'set_node' 
yes I know that is not a real object, but it is a result of not being able to load a mapblock, which was the real issue: 
<pre>
2016-04-05 11:14:58,453 map:load                     :480  DEBUG    Mapblock 176
 not found
</pre>
if I just initialized a block with init_mapblock(Pos.getAsInt()) then why can't I load a mapblock with load(Pos.getAsInt()), and why can't init_mapblock just return the block object or at least the kind of objectID needed for load()? or in otherwords, how do I get the objectID from the object Pos?

>set_node needs pos

When I try to use a Pos object, as I do by https://gist.github.com/bobombolo/1e430eff993b7029b1030582d725f164#file-preload-py-L105

and pass that to set_node by https://gist.github.com/bobombolo/1e430eff993b7029b1030582d725f164#file-preload-py-L121 

i still get the following error which states that it is of type string: 

<pre>
Traceback (most recent call last):
  File "preload.py", line 121, in <module>
    map_interface.set_node(node["pos"], cover[node["lclu"]])
  File "C:\Python34\lib\libminetest\map.py", line 649, in set_node
    node.pos = pos
AttributeError: 'str' object has no attribute 'pos'
</pre>

**Comment by bobombolo** [comment]
i have avoided these issues with different approaches and also figured out some mistakes i made. i will refactor this issue into more specific bugs if they are indeed persisting

**Comment by bobombolo** [comment]
Maybe you can just try this script. The outstanding issues are that no nodes are actually ever set in the try: set_node() section (line 121), I think there is a problem with initializing and loading mapblocks due to different position formats?

https://gist.github.com/bobombolo/1e430eff993b7029b1030582d725f164

<pre>
2016-04-05 15:24:10,031 map:load_mapblock            :591  DEBUG    Loaded mapbl
ock at -16760826
2016-04-05 15:24:10,031 map:load                     :480  DEBUG    Mapblock -16
760826 not found
2016-04-05 15:24:10,031 map:load_mapblock            :594  DEBUG    Mapblock is
None
2016-04-05 15:24:10,031 map:init_mapblock            :622  DEBUG    Init mapbloc
k at 3910
2016-04-05 15:24:10,031 map:__init__                 :35   DEBUG    MapBlock obj
ect initiated at (3910, 0, 0)
2016-04-05 15:24:10,046 map:load_mapblock            :591  DEBUG    Loaded mapbl
ock at -16760826
2016-04-05 15:24:10,046 map:load                     :480  DEBUG    Mapblock -16
760826 not found
2016-04-05 15:24:10,062 map:load_mapblock            :594  DEBUG    Mapblock is
None
2016-04-05 15:24:10,062 map:init_mapblock            :622  DEBUG    Init mapbloc
k at 3910
2016-04-05 15:24:10,062 map:__init__                 :35   DEBUG    MapBlock obj
ect initiated at (3910, 0, 0)
2016-04-05 15:24:10,078 map:load_mapblock            :591  DEBUG    Loaded mapbl
ock at -16760826
2016-04-05 15:24:10,078 map:load                     :480  DEBUG    Mapblock -16
760826 not found
2016-04-05 15:24:10,078 map:load_mapblock            :594  DEBUG    Mapblock is
None
2016-04-05 15:24:10,078 map:init_mapblock            :622  DEBUG    Init mapbloc
k at 3910
2016-04-05 15:24:10,078 map:__init__                 :35   DEBUG    MapBlock obj
ect initiated at (3910, 0, 0)
2016-04-05 15:24:10,125 map:load_mapblock            :591  DEBUG    Loaded mapbl
ock at -16760826
</pre>
etc

**Comment by bobombolo** [comment]
perhaps determineMapBlock() is not updated for the new position style?

**Comment by bobombolo** [comment]
whatever I did I have the script working and will start a new issue elsewhere for optimizing it!

**Comment by ghost** [comment]
actually I have not solved the init_mapblock issue, the reason it started working is because I entered the map and explored around, initializing the area of interest, so that when I ran the script again set_node just worked because nothing needed to be initialized. can you look at my script and see why the init_mapblock doesn't work? I moved it from a gist to a repo:

https://github.com/bobombolo/preload/blob/master/preload.py#L146-L161

you can see i have commented out some alternate approaches (initializing mapblocks that I know are not initialized in an empty map.sqlite file, trying to use mapBlock.load() and map.Block.write() incorrectly...

also, is there a way to use MapBlock() to init and create a MapBlock instance instead of MapInterface.init_mapblock()?

**Comment by Lymkwi** [comment]
> also, is there a way to use MapBlock() to init and create a MapBlock instance instead of MapInterface.init_mapblock()?

You could create a mapblock in your code, insert it in the MapInterface's cache, and its id in the object's stackcaches, then call check_cache() to check whether the cache is overflowing or not ; but that's exactly what init_mapblock() is doing for you.
If you plan on using a MapVessel directly though, you can now initialize your own mapblocks and write them manually with MapVessel.write(blockID, binary_blob).

I'm pretty sure the sole reason why your script didn't work was the stupid mistake I fixed in #8. In your code, you could initialize your own mapblock, write all the nodes you need in it, then write it using the MapVessel object of your MapInterface. That would probably be the most efficient was of inserting those nodes.
I'm going to rework your script right now, and see if that method works (it should).
EDIT: Actually, since you import a schematic, there is no way you can bypass the MapInterface..

**Comment by ghost** [comment]
well I can do that schematic import as a separate step, I'm curious to see how you would do what you are discussing about manually updating mapblocks.

**Comment by Lymkwi** [comment]
It would look like that (without schematics, comments, etc):

``` python
for mapblocky in blocks:
    mapblockpos = libminetest.utils.Pos(mapx, mapblocky, mapz)
    mbobj = libminetest.map.MapBlock(abspos = mapblockpos.getAsInt(max_val=4096))

    for node in blocks[mapblocky]:
        npos = libminetest.utils.Pos(node["pos"].x % 16, node["pos"].y % 16, node["pos"].z % 16)
        mbobj.set_node(npos.getAsInt(), cover[node["lclu"]])
        t = t+1

    #then write the block
    map_interface.container.write(mapblockpos.getAsInt(max_val=4096), mbobj.implode())
    #reporting
    print("[BLOCK: {block}] [ELAPSED: {elapsed:.2f}s] [READ: {read:.4f}%] [WROTE: {wrote:.4f}%]".format(
        block=str(mapblockpos),
        elapsed=(time()-s),
        read=((p/tpix)*100),
        wrote=((t/tpix)*100)
    ))
```

**Comment by ghost** [comment]
hey that fixed another issue with missing nodes. 
https://github.com/bobombolo/preload/issues/6
thanks.

**Comment by ghost** [comment]
I think there is still an issue somewhere, and since I haven't changed the logic of the script, I am wondering if there is still an issue with the lib. if I use the original method of map_interface set_node() I get some missing nodes, and if I use your code there is a shift of 15 of the 16 rows in every block being shifted 16 spaces to the north, which I didn't realise because I used a test map of 32x32 nodes all on y=0 so it looked at a glance like it was correct but it is shifted to the north. it is much more obvious on a real terrain, creating strange hoops which made it obvious.
see https://github.com/bobombolo/preload/issues/11

(before your code snippet was implemented the defect of holes looked like: https://github.com/bobombolo/preload/issues/6

**Comment by Lymkwi** [comment]
The only mathematical explanation I have is the modulo screwing up everything... Which wouldn't make sense.. But I haven't seen any issues on my own scripts when loading images or large schematics..
